version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-staging
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=4000
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:4000/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
