version: '3.8'

services:
  nestjs-app:
    build: .
    container_name: nestjs-staging
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=4000
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
