services:
  nestjs-app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: nestjs-staging
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      - NODE_ENV=staging
      - PORT=4000
    restart: unless-stopped
    command: sh -c "yarn prisma migrate deploy && yarn start:prod"
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:4000/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
